version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi-tracker
    ports:
      - "8002:8002"
    volumes:
      - fastapi_data:/app/fastapi_data
    environment:
      - DATABASE_URL=sqlite:////app/fastapi_data/tracking.db
    restart: always

volumes:
  fastapi_data:
