version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi-tracker
    expose:
      - "8002"
    volumes:
      - app_data:/app/app/data
    restart: always

  nginx:
    build: ./frontend
    container_name: nginx-tracker
    ports:
      - "80:80"
    depends_on:
      - fastapi
    restart: always

volumes:
  app_data:
